name: Build NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore packages
      run: |
           for s in 2022 2021 2020; do
               dotnet restore $s/AdventOfCode$s.sln
           done

    - name: Install Coverlet
      run: dotnet tool install --global coverlet.console

    - name: Build solutions
      run: |
           for s in 2022 2021 2020; do
               dotnet build --configuration Debug --no-restore $s/AdventOfCode$s.sln /p:DefineConstants="CI_CONTEXT"
           done

    - name: Testing projects
      run: |
           for s in 2022 2021 2020; do
               for d in `seq 25`; do
                   coverlet $s/Day$d/Day$d.UnitTests/bin/Debug/net7/Day$d.UnitTests.dll --target "dotnet" --targetargs "test $s/Day$d/Day$d.UnitTests/Day$d.UnitTests.csproj --no-build" --format OpenCover --output adventofcode-$s-day$d.coverage.xml
               done
           done

    - name: Upload coverage to CodeCov
      run: bash <(curl -s https://codecov.io/bash)

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: ./*.coverage.xml
